name: Deploy site

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  terraform:
    needs: build
    uses: ./.github/workflows/terraform.yml
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      CUSTOM_DOMAIN: ${{ vars.CUSTOM_DOMAIN }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN}}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      ZONE_ID: ${{ secrets.ZONE_ID }}
