name: Deploy site

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  terraform:
    needs: build
    uses: ./.github/workflows/terraform.yml
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
