name: Terraform orchestration

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
        description: "The name of the downloaded artifact"

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN}}
      TF_VAR_account_id: ${{ secrets.ACCOUNT_ID }}
      TF_VAR_zone_id: ${{ secrets.ZONE_ID }}
      TF_VAR_custom_domain: ${{ vars.CUSTOM_DOMAIN }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v7
        with:
          name: ${{ inputs.artifact-name }}
          path: dist
      - uses: hashicorp/setup-terraform@v4
      - run: terraform init -input=false --reconfigure
        working-directory: terraform
      - run: terraform validate
        working-directory: terraform
      - run: terraform plan -out=tfplan -input=false
        working-directory: terraform
      - run: terraform apply -input=false -auto-approve tfplan
        working-directory: terraform
